DELETE FROM tbl_servprov_share WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_return_aging_b WHERE NAME LIKE `${dataPrefix}`
DELETE FROM tbl_charging_agreement WHERE XID LIKE `${dataPrefix}`
DELETE FROM tbl_charging_rule WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_customer_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_oil_b WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_servprov_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM tbl_charging_agreement WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_aging_b WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_distance_b WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_servprov_rule_b WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_item_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_contact_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_equipment_group_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_equipment_group_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_equipment_group_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_calendar WHERE XID LIKE `${dataPrefix}`
DELETE FROM tbl_distribution_route WHERE NAME LIKE `${dataPrefix}`
DELETE FROM tbl_distribution_route WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_area_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_location_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_item_type_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_fee_class_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_fee_type_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_transport_mode_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_order_type_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM tbl_rule WHERE XID LIKE `${dataPrefix}`
DELETE FROM tbl_rule_group WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_business_unit_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM tbl_route_rule WHERE NAME LIKE `${dataPrefix}`
DELETE FROM basic_document_type WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_equipment_b WHERE XID LIKE `${dataPrefix}`
DELETE FROM basic_driver_b WHERE XID LIKE `${dataPrefix}`
